<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.aws.codestar.projecttemplates</groupId>
    <artifactId>Kav_Devops</artifactId>
    <version>3.3.6-SNAPSHOT</version>
    <!-- <version>9.10.3-SNAPSHOT</version> -->
    <packaging>war</packaging>
    <name>Kav_DevOps - Sample Spring MVC Application</name>

    <properties>
        <junit.platform.version>1.2.0</junit.platform.version>
        <junit.jupiter.version>5.2.0</junit.jupiter.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>

<!-- # add copied maven SonarQube code here  -->

       <sonar.host.url>http://54.234.216.203:9000</sonar.host.url>
        <sonar.organization>Kav_DevOps</sonar.organization>
        <sonar.projectKey>Kav_Dev_Pro</sonar.projectKey>
        <sonar.login>sqp_8f13915ee2350315aaebd9acd6a479ba3598dbb0</sonar.login>


      <!-- mvn clean verify sonar:sonar \
  -Dsonar.projectKey=Kav_DevOps_Pro \
  -Dsonar.host.url=http://54.198.125.165:9000 \
  -Dsonar.login=sqp_a124c2adc481d105d6545cd5dfaecea11659b934 -->


    </properties>

       
     <!-- # Update JFrog Artifactory repository URLs - release and snapshot repositories -->
<distributionManagement>

    <repository>
        <id>ksv-release</id>
        <name>kav-libs-release-local</name>
        <url>http://54.234.34.73:8082/artifactory/kav-libs-release-local/</url>
    </repository>

    <snapshotRepository>
        <id>ksv-snapshots</id>
        <name>kav-libs-snapshots-local</name>
        <url>http://54.234.34.73:8082/artifactory/kav-libs-snapshots-local/</url>
    </snapshotRepository>

</distributionManagement>

    
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>5.0.7.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>5.0.7.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>5.0.7.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>5.0.7.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
            <version>1.3.3</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>${junit.platform.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-runner</artifactId>
            <version>${junit.platform.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>3.2.2</version>
                    <configuration>
                        <warSourceDirectory>src/main/webapp</warSourceDirectory>
                        <warName>devops</warName>
                        <failOnMissingWebXml>false</failOnMissingWebXml>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.22.0</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.junit.platform</groupId>
                            <artifactId>junit-platform-surefire-provider</artifactId>
                            <version>${junit.platform.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.junit.jupiter</groupId>
                            <artifactId>junit-jupiter-engine</artifactId>
                            <version>${junit.jupiter.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </pluginManagement>
        <finalName>devops</finalName>
    </build>
</project>
